name: nyanya
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: aaa
        run: |
          git checkout -b pg
          ls
          find . -name "*.md" -exec git rm {} \;
      - name: push
        run: git push --force origin pg
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
